import {
  insert
} from '../src';
export function fixtures() {

  [{
    "CustomerID": "ALFKI",
    "CompanyName": "Alfreds Futterkiste",
    "ContactName": "Maria Anders",
    "ContactTitle": "Sales Representative",
    "Address": "Obere Str. 57",
    "City": "Berlin",
    "Region": null,
    "PostalCode": "12209",
    "Country": "Germany",
    "Phone": "030-0074321",
    "Fax": "030-0076545"
  }, {
    "CustomerID": "ANATR",
    "CompanyName": "Ana Trujillo Emparedados y helados",
    "ContactName": "Ana Trujillo",
    "ContactTitle": "Owner",
    "Address": "Avda. de la ConstituciÃ³n 2222",
    "City": "MÃ©xico D.F.",
    "Region": null,
    "PostalCode": "05021",
    "Country": "Mexico",
    "Phone": "(5) 555-4729",
    "Fax": "(5) 555-3745"
  }, {
    "CustomerID": "ANTON",
    "CompanyName": "Antonio Moreno TaquerÃ­a",
    "ContactName": "Antonio Moreno",
    "ContactTitle": "Owner",
    "Address": "Mataderos  2312",
    "City": "MÃ©xico D.F.",
    "Region": null,
    "PostalCode": "05023",
    "Country": "Mexico",
    "Phone": "(5) 555-3932",
    "Fax": null
  }, {
    "CustomerID": "AROUT",
    "CompanyName": "Around the Horn",
    "ContactName": "Thomas Hardy",
    "ContactTitle": "Sales Representative",
    "Address": "120 Hanover Sq.",
    "City": "London",
    "Region": null,
    "PostalCode": "WA1 1DP",
    "Country": "UK",
    "Phone": "(171) 555-7788",
    "Fax": "(171) 555-6750"
  }, {
    "CustomerID": "BERGS",
    "CompanyName": "Berglunds snabbkÃ¶p",
    "ContactName": "Christina Berglund",
    "ContactTitle": "Order Administrator",
    "Address": "BerguvsvÃ¤gen  8",
    "City": "LuleÃ¥",
    "Region": null,
    "PostalCode": "S-958 22",
    "Country": "Sweden",
    "Phone": "0921-12 34 65",
    "Fax": "0921-12 34 67"
  }, {
    "CustomerID": "BLAUS",
    "CompanyName": "Blauer See Delikatessen",
    "ContactName": "Hanna Moos",
    "ContactTitle": "Sales Representative",
    "Address": "Forsterstr. 57",
    "City": "Mannheim",
    "Region": null,
    "PostalCode": "68306",
    "Country": "Germany",
    "Phone": "0621-08460",
    "Fax": "0621-08924"
  }].forEach(customer => insert('customer', customer));


  [
 {
   "ProductID": 1,
   "ProductName": "Chai",
   "SupplierID": 1,
   "CategoryID": 1,
   "QuantityPerUnit": "10 boxes x 20 bags",
   "UnitPrice": 18,
   "UnitsInStock": 39,
   "UnitsOnOrder": 0,
   "ReorderLevel": 10,
   "Discontinued": 0
 },
 {
   "ProductID": 2,
   "ProductName": "Chang",
   "SupplierID": 1,
   "CategoryID": 1,
   "QuantityPerUnit": "24 - 12 oz bottles",
   "UnitPrice": 19,
   "UnitsInStock": 17,
   "UnitsOnOrder": 40,
   "ReorderLevel": 25,
   "Discontinued": 0
 },
 {
   "ProductID": 3,
   "ProductName": "Aniseed Syrup",
   "SupplierID": 1,
   "CategoryID": 2,
   "QuantityPerUnit": "12 - 550 ml bottles",
   "UnitPrice": 10,
   "UnitsInStock": 13,
   "UnitsOnOrder": 70,
   "ReorderLevel": 25,
   "Discontinued": 0
 },
 {
   "ProductID": 4,
   "ProductName": "Chef Anton's Cajun Seasoning",
   "SupplierID": 2,
   "CategoryID": 2,
   "QuantityPerUnit": "48 - 6 oz jars",
   "UnitPrice": 22,
   "UnitsInStock": 53,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 5,
   "ProductName": "Chef Anton's Gumbo Mix",
   "SupplierID": 2,
   "CategoryID": 2,
   "QuantityPerUnit": "36 boxes",
   "UnitPrice": 21.35,
   "UnitsInStock": 0,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 1
 },
 {
   "ProductID": 6,
   "ProductName": "Grandma's Boysenberry Spread",
   "SupplierID": 3,
   "CategoryID": 2,
   "QuantityPerUnit": "12 - 8 oz jars",
   "UnitPrice": 25,
   "UnitsInStock": 120,
   "UnitsOnOrder": 0,
   "ReorderLevel": 25,
   "Discontinued": 0
 },
 {
   "ProductID": 7,
   "ProductName": "Uncle Bob's Organic Dried Pears",
   "SupplierID": 3,
   "CategoryID": 7,
   "QuantityPerUnit": "12 - 1 lb pkgs.",
   "UnitPrice": 30,
   "UnitsInStock": 15,
   "UnitsOnOrder": 0,
   "ReorderLevel": 10,
   "Discontinued": 0
 },
 {
   "ProductID": 8,
   "ProductName": "Northwoods Cranberry Sauce",
   "SupplierID": 3,
   "CategoryID": 2,
   "QuantityPerUnit": "12 - 12 oz jars",
   "UnitPrice": 40,
   "UnitsInStock": 6,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 9,
   "ProductName": "Mishi Kobe Niku",
   "SupplierID": 4,
   "CategoryID": 6,
   "QuantityPerUnit": "18 - 500 g pkgs.",
   "UnitPrice": 97,
   "UnitsInStock": 29,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 1
 },
 {
   "ProductID": 10,
   "ProductName": "Ikura",
   "SupplierID": 4,
   "CategoryID": 8,
   "QuantityPerUnit": "12 - 200 ml jars",
   "UnitPrice": 31,
   "UnitsInStock": 31,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 11,
   "ProductName": "Queso Cabrales",
   "SupplierID": 5,
   "CategoryID": 4,
   "QuantityPerUnit": "1 kg pkg.",
   "UnitPrice": 21,
   "UnitsInStock": 22,
   "UnitsOnOrder": 30,
   "ReorderLevel": 30,
   "Discontinued": 0
 },
 {
   "ProductID": 12,
   "ProductName": "Queso Manchego La Pastora",
   "SupplierID": 5,
   "CategoryID": 4,
   "QuantityPerUnit": "10 - 500 g pkgs.",
   "UnitPrice": 38,
   "UnitsInStock": 86,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 13,
   "ProductName": "Konbu",
   "SupplierID": 6,
   "CategoryID": 8,
   "QuantityPerUnit": "2 kg box",
   "UnitPrice": 6,
   "UnitsInStock": 24,
   "UnitsOnOrder": 0,
   "ReorderLevel": 5,
   "Discontinued": 0
 },
 {
   "ProductID": 14,
   "ProductName": "Tofu",
   "SupplierID": 6,
   "CategoryID": 7,
   "QuantityPerUnit": "40 - 100 g pkgs.",
   "UnitPrice": 23.25,
   "UnitsInStock": 35,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 15,
   "ProductName": "Genen Shouyu",
   "SupplierID": 6,
   "CategoryID": 2,
   "QuantityPerUnit": "24 - 250 ml bottles",
   "UnitPrice": 15.5,
   "UnitsInStock": 39,
   "UnitsOnOrder": 0,
   "ReorderLevel": 5,
   "Discontinued": 0
 },
 {
   "ProductID": 16,
   "ProductName": "Pavlova",
   "SupplierID": 7,
   "CategoryID": 3,
   "QuantityPerUnit": "32 - 500 g boxes",
   "UnitPrice": 17.45,
   "UnitsInStock": 29,
   "UnitsOnOrder": 0,
   "ReorderLevel": 10,
   "Discontinued": 0
 },
 {
   "ProductID": 17,
   "ProductName": "Alice Mutton",
   "SupplierID": 7,
   "CategoryID": 6,
   "QuantityPerUnit": "20 - 1 kg tins",
   "UnitPrice": 39,
   "UnitsInStock": 0,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 1
 },
 {
   "ProductID": 18,
   "ProductName": "Carnarvon Tigers",
   "SupplierID": 7,
   "CategoryID": 8,
   "QuantityPerUnit": "16 kg pkg.",
   "UnitPrice": 62.5,
   "UnitsInStock": 42,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 19,
   "ProductName": "Teatime Chocolate Biscuits",
   "SupplierID": 8,
   "CategoryID": 3,
   "QuantityPerUnit": "10 boxes x 12 pieces",
   "UnitPrice": 9.2,
   "UnitsInStock": 25,
   "UnitsOnOrder": 0,
   "ReorderLevel": 5,
   "Discontinued": 0
 },
 {
   "ProductID": 20,
   "ProductName": "Sir Rodney's Marmalade",
   "SupplierID": 8,
   "CategoryID": 3,
   "QuantityPerUnit": "30 gift boxes",
   "UnitPrice": 81,
   "UnitsInStock": 40,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 21,
   "ProductName": "Sir Rodney's Scones",
   "SupplierID": 8,
   "CategoryID": 3,
   "QuantityPerUnit": "24 pkgs. x 4 pieces",
   "UnitPrice": 10,
   "UnitsInStock": 3,
   "UnitsOnOrder": 40,
   "ReorderLevel": 5,
   "Discontinued": 0
 },
 {
   "ProductID": 22,
   "ProductName": "Gustaf's Knäckebröd",
   "SupplierID": 9,
   "CategoryID": 5,
   "QuantityPerUnit": "24 - 500 g pkgs.",
   "UnitPrice": 21,
   "UnitsInStock": 104,
   "UnitsOnOrder": 0,
   "ReorderLevel": 25,
   "Discontinued": 0
 },
 {
   "ProductID": 23,
   "ProductName": "Tunnbröd",
   "SupplierID": 9,
   "CategoryID": 5,
   "QuantityPerUnit": "12 - 250 g pkgs.",
   "UnitPrice": 9,
   "UnitsInStock": 61,
   "UnitsOnOrder": 0,
   "ReorderLevel": 25,
   "Discontinued": 0
 },
 {
   "ProductID": 24,
   "ProductName": "Guaraná Fantástica",
   "SupplierID": 10,
   "CategoryID": 1,
   "QuantityPerUnit": "12 - 355 ml cans",
   "UnitPrice": 4.5,
   "UnitsInStock": 20,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 1
 },
 {
   "ProductID": 25,
   "ProductName": "NuNuCa Nuß-Nougat-Creme",
   "SupplierID": 11,
   "CategoryID": 3,
   "QuantityPerUnit": "20 - 450 g glasses",
   "UnitPrice": 14,
   "UnitsInStock": 76,
   "UnitsOnOrder": 0,
   "ReorderLevel": 30,
   "Discontinued": 0
 },
 {
   "ProductID": 26,
   "ProductName": "Gumbär Gummibärchen",
   "SupplierID": 11,
   "CategoryID": 3,
   "QuantityPerUnit": "100 - 250 g bags",
   "UnitPrice": 31.23,
   "UnitsInStock": 15,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 0
 },
 {
   "ProductID": 27,
   "ProductName": "Schoggi Schokolade",
   "SupplierID": 11,
   "CategoryID": 3,
   "QuantityPerUnit": "100 - 100 g pieces",
   "UnitPrice": 43.9,
   "UnitsInStock": 49,
   "UnitsOnOrder": 0,
   "ReorderLevel": 30,
   "Discontinued": 0
 },
 {
   "ProductID": 28,
   "ProductName": "Rössle Sauerkraut",
   "SupplierID": 12,
   "CategoryID": 7,
   "QuantityPerUnit": "25 - 825 g cans",
   "UnitPrice": 45.6,
   "UnitsInStock": 26,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 1
 },
 {
   "ProductID": 29,
   "ProductName": "Thüringer Rostbratwurst",
   "SupplierID": 12,
   "CategoryID": 6,
   "QuantityPerUnit": "50 bags x 30 sausgs.",
   "UnitPrice": 123.79,
   "UnitsInStock": 0,
   "UnitsOnOrder": 0,
   "ReorderLevel": 0,
   "Discontinued": 1
 },
 {
   "ProductID": 30,
   "ProductName": "Nord-Ost Matjeshering",
   "SupplierID": 13,
   "CategoryID": 8,
   "QuantityPerUnit": "10 - 200 g glasses",
   "UnitPrice": 25.89,
   "UnitsInStock": 10,
   "UnitsOnOrder": 0,
   "ReorderLevel": 15,
   "Discontinued": 0
 },
 {
   "ProductID": 31,
   "ProductName": "Gorgonzola Telino",
   "SupplierID": 14,
   "CategoryID": 4,
   "QuantityPerUnit": "12 - 100 g pkgs",
   "UnitPrice": 12.5,
   "UnitsInStock": 0,
   "UnitsOnOrder": 70,
   "ReorderLevel": 20,
   "Discontinued": 0
 },
 {
   "ProductID": 32,
   "ProductName": "Mascarpone Fabioli",
   "SupplierID": 14,
   "CategoryID": 4,
   "QuantityPerUnit": "24 - 200 g pkgs.",
   "UnitPrice": 32,
   "UnitsInStock": 9,
   "UnitsOnOrder": 40,
   "ReorderLevel": 25,
   "Discontinued": 0
 },
 {
   "ProductID": 33,
   "ProductName": "Geitost",
   "SupplierID": 15,
   "CategoryID": 4,
   "QuantityPerUnit": "500 g",
   "UnitPrice": 2.5,
   "UnitsInStock": 112,
   "UnitsOnOrder": 0,
   "ReorderLevel": 20,
   "Discontinued": 0
 }].forEach(product => insert('product', product));
}
